from models.attractions.wetlands import Wetlands
from models.attractions.petting_zoo import PettingZoo
from models.attractions.snake_pit import SnakePit
from animals import Alligator, Copperhead, Dolphin, Eel, Giraffe, Goldfish, Hippo, Llama, Monkey, Octopus, Rat_Snake, Salamander, Snail, Starfish, Tiger

miss_fuzz = Llama("Miss Fuzz", "domestic llama", "afternoon")
tony = Tiger("Tony", "hungry tiger", "morning")
ned = Giraffe("Ned", "friendly giraffe", "evening")
henry = Hippo("Henry", "hippopotamus", "afternoon")
george = Monkey("George", "chimpanzee", "morning", 527)
flipper = Dolphin("Flipper", "wild dolphin", "afternoon")
buddha = Starfish("Buddha", "golden starfish", "morning")
ed = Eel("Ed", "electric eel", "evening")
gus = Octopus("Gus", "wild octopus", "evening")
jerry = Goldfish("Jerry", "wild octopus", "morning")
carl = Copperhead("Carl", "copperhead snake", "morning")
ren = Rat_Snake("Ren", "poisonous rattler", "afternoon")
sally = Salamander("Sally", "domestic salamander", "afternoon")
charlie = Snail("Charile", "domestic snail", "afternoon")
al = Alligator("Al", "dangerous gator", "afternoon")

slither_inn = SnakePit("Slither Inn")
varmint_village = PettingZoo("Varmint Village")
water_town = Wetlands("Water Town")

slither_inn.add_animal(carl)
slither_inn.add_animal(ren)
slither_inn.add_animal(sally)
slither_inn.add_animal(charlie)
slither_inn.add_animal(al)
varmint_village.add_animal(miss_fuzz)
varmint_village.add_animal(tony)
varmint_village.add_animal(ned)
varmint_village.add_animal(henry)
varmint_village.add_animal(george)
water_town.add_animal(flipper)
water_town.add_animal(buddha)
water_town.add_animal(ed)
water_town.add_animal(gus)
water_town.add_animal(jerry)


print(miss_fuzz)
print(tony)
print(ned)
print(henry)
print(george)
print(flipper)
print(buddha)
print(ed)
print(gus)
print(jerry)
print(carl)
print(ren)
print(sally)
print(charlie)
print(al)
print(slither_inn)
print(varmint_village)
print(water_town)

george.chip_number = 21
print(george.chip_number)

print(slither_inn.last_critter_added)
print(varmint_village.last_critter_added)
print(water_town.last_critter_added)