from .alligator import Alligator
from .copperhead import Copperhead
from .dolphin import Dolphin
from .eel import Eel
from .giraffe import Giraffe
from .goldfish import Goldfish
from .hippo import Hippo
from .llama import Llama
from .monkey import Monkey
from .octopus import Octopus
from .rat_snake import Rat_Snake
from .salamander import Salamander
from .snail import Snail
from .starfish import Starfish
from .tiger import Tiger